baseURL = "https://hen99-csy.github.io/hye-eun/"
languageCode = "ko-KR"
title = "혜은의 공간"
theme = "PaperMod"
[params]
author = "혜은"
defaultTheme = "auto"
[params.profileMode]
enabled = true
title = "안녕하세요! 개발자 혜은입니다 👩‍💻"
subtitle = "이곳은 저의 포트폴리오와 일상, 그리고 위시리스트를 기록하는 공간입니다. 방문해 주셔서 감사합니다!"
imageUrl = "profile.jpg"
imageWidth = 150
imageHeight = 250
[[params.profileMode.buttons]]
name = "🎁 나의 위시리스트"
url = "/hye-eun/wishlist/"
[[params.profileMode.buttons]]
name = "📅 일정 정보"
url = "/hye-eun/schedule/"
[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/hen"
[[params.socialIcons]]
name = "github"
url = "https://github.com/hen99-csy"